[package]
name = "cargo-sync-rdme"
version = "0.5.2"
edition.workspace = true
rust-version.workspace = true
description = "Cargo subcommand to synchronize README with crate documentation"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = []
categories = []

[package.metadata.cargo-sync-rdme]
extra-targets = "./docs/configuration.md"

[package.metadata.cargo-sync-rdme.badge]
style = "flat-square"

[package.metadata.cargo-sync-rdme.badge.badges]
maintenance = true
license = { link = "#license" }
crates-io = true
docs-rs = true
rust-version = true
github-actions = { workflows = ["ci.yml"] }
codecov = true

[package.metadata.cargo-sync-rdme.badge.badges-maintenance]
maintenance = true

[package.metadata.cargo-sync-rdme.badge.badges-license]
license = true

[package.metadata.cargo-sync-rdme.badge.badges-crates-io]
crates-io = true

[package.metadata.cargo-sync-rdme.badge.badges-docs-rs]
docs-rs = true

[package.metadata.cargo-sync-rdme.badge.badges-rust-version]
rust-version = true

[package.metadata.cargo-sync-rdme.badge.badges-github-actions]
github-actions = true

[package.metadata.cargo-sync-rdme.badge.badges-codecov]
codecov = true

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.'cfg(target_os = "windows")']
pkg-fmt = "zip"

[workspace]
members = ["examples/lib"]

[workspace.package]
edition = "2024"
rust-version = "1.88.0"
repository = "https://github.com/gifnksm/cargo-sync-rdme"
license = "MIT OR Apache-2.0"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

# Restriction group
allow_attributes = "warn"
assertions_on_result_states = "warn"
clone_on_ref_ptr = "warn"
doc_paragraphs_missing_punctuation = "warn"
error_impl_error = "warn"
filetype_is_file = "warn"
get_unwrap = "warn"
if_then_some_else_none = "warn"
impl_trait_in_params = "warn"
map_err_ignore = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_self_imports = "warn"
unused_trait_names = "warn"
verbose_file_reads = "warn"

[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
keyword_idents = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
missing_unsafe_on_extern = "warn"
redundant_imports = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unreachable_pub = "warn"
unsafe_attr_outside_unsafe = "warn"
unused_crate_dependencies = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[workspace.lints.rustdoc]
missing_crate_level_docs = "warn"
private_doc_tests = "warn"
unescaped_backticks = "warn"

[dependencies]
cargo_metadata = "0.23.1"
clap = { version = "4.6.4", features = ["derive"] }
clap_complete = "4.6.7"
clap_complete_nushell = "4.6.1"
clap_mangen = "0.3.0"
console = "0.16.4"
git2 = { version = "0.21.0", default-features = false, optional = true }
miette = { version = "7.6.0", features = ["fancy"] }
pulldown-cmark = "0.13.4"
pulldown-cmark-to-cmark = "22.0.0"
rustdoc-types = "0.61.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
similar = { version = "3.1.1", features = ["inline", "unicode"] }
tempfile = "3.27.0"
thiserror = "2.0.19"
toml = { version = "1.1.3", features = ["preserve_order"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = "2.5.8"
void = "1.0.2"

[dev-dependencies]
indoc = "2.0.7"

[build-dependencies]

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["vcs-git"]
vcs-git = ["dep:git2"]
vendored-libgit2 = ["git2?/vendored-libgit2"]

[lints]
workspace = true

[profile.release]
strip = true
