[package]
name = "cargo-sync-rdme"
version = "0.6.0"
edition.workspace = true
rust-version.workspace = true
description = "Cargo subcommand to synchronize README with crate documentation"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["cargo", "documentation", "readme", "rustdoc", "subcommand"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]

[package.metadata.cargo-sync-rdme]
extra-targets = "./docs/configuration.md"

[package.metadata.cargo-sync-rdme.badge]
style = "flat-square"
badges = {
  maintenance = true,
  license = { link = "#license" },
  crates-io = true,
  rust-version = true,
  github-actions = { workflows = ["ci.yml"] },
  codecov = true,
}
badges-maintenance = { maintenance = true }
badges-license = { license = true }
badges-crates-io = { crates-io = true }
badges-docs-rs = { docs-rs = true }
badges-rust-version = { rust-version = true }
badges-github-actions = { github-actions = true }
badges-codecov = { codecov = true }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.'cfg(target_os = "windows")']
pkg-fmt = "zip"

[workspace]
members = ["examples/lib"]

[workspace.package]
edition = "2024"
rust-version = "1.96.0"
repository = "https://github.com/gifnksm/cargo-sync-rdme"
license = "MIT OR Apache-2.0"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

# Restriction group
allow_attributes = "warn"
assertions_on_result_states = "warn"
clone_on_ref_ptr = "warn"
doc_paragraphs_missing_punctuation = "warn"
error_impl_error = "warn"
filetype_is_file = "warn"
get_unwrap = "warn"
if_then_some_else_none = "warn"
impl_trait_in_params = "warn"
map_err_ignore = "warn"
self_named_module_files = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_self_imports = "warn"
unused_trait_names = "warn"
verbose_file_reads = "warn"

[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
keyword_idents = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
missing_unsafe_on_extern = "warn"
redundant_imports = "warn"
single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unreachable_pub = "warn"
unsafe_attr_outside_unsafe = "warn"
unused_crate_dependencies = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[workspace.lints.rustdoc]
missing_crate_level_docs = "warn"
private_doc_tests = "warn"
unescaped_backticks = "warn"

[dependencies]
cargo_metadata = "0.23.1"
clap = { version = "4.6.6", features = ["derive"] }
clap_complete = "4.6.9"
clap_complete_nushell = "4.6.1"
clap_mangen = "0.3.2"
console = "0.16.4"
miette = { version = "7.6.0", features = ["fancy"] }
pulldown-cmark = "0.13.4"
pulldown-cmark-to-cmark = "22.0.1"
rustdoc-types = "0.61.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
similar = { version = "3.1.2", features = ["inline", "unicode"] }
tempfile = "3.27.0"
thiserror = "2.0.20"
toml = { version = "1.1.4", features = ["preserve_order"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
unicase = "2.9.0"
url = "2.5.8"
vcs-modify-guard = { version = "0.1.0", default-features = false }
void = "1.0.2"

[dev-dependencies]
indoc = "2.0.7"

[build-dependencies]

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["vcs-git"]
vcs-git = ["vcs-modify-guard/git-default"]

[lints]
workspace = true

[profile.release]
strip = true
