["audit:advisories"]
description = "Run cargo-deny to check for advisories"
run = "cargo deny check advisories"

["audit:policy"]
description = "Run cargo-deny to check for policy violations"
run = "cargo deny check bans licenses sources"
