["sync:markdown"]
description = "Synchronize Markdown files with Rust doc comments"
usage = '''
flag "--check" help="Run cargo-sync-rdme in check mode"
flag "--allow-dirty" help="Sync Markdown files even if the target file is dirty"
'''
depends = ["install-toolchains-for-sync-rdme"]
run = '''
cargo run -- --workspace
  {{- ' --check' if usage.check else '' }}
  {{- ' --allow-dirty' if usage.allow_dirty else '' }}
'''

["lint:markdown"]
description = "Lint Markdown files"
run = "markdownlint ."
