[pre-release]
run = [
  { task = "sync:markdown --allow-dirty" },
  '''
  {% if env.GITHUB_ACTIONS != 'true' %}
  mise run ci
  {% endif %}
  '''
]

["check:release"]
run = "cargo release patch -vv --allow-branch '*'"
