//! Integration test to ensure that the generated links match the links generated by rustdoc.

#![allow(unused_crate_dependencies)]

use std::{
    env, fs,
    path::{Path, PathBuf},
    sync::Once,
};

use assert_cmd::Command;
use assert_fs::{TempDir, prelude::*};
use pulldown_cmark::{Event, Parser, Tag};
use rstest::rstest;
use scraper::{Html, Selector};
use similar_asserts::assert_eq;

const SPAN_START_MARKER: &str = "<!-- SYNC_RDME_INTEGRATION_TEST::SPAN_START -->";
const SPAN_END_MARKER: &str = "<!-- SYNC_RDME_INTEGRATION_TEST::SPAN_END -->";
const HTML_ROOT_URL: &str = "https://example.com/html_root/";

// `cargo test` runs these rstest cases in parallel. When the nightly toolchain is
// not installed yet, having multiple cases probe `+nightly` concurrently can make
// rustup trip over itself while installing it. Probe `rustc +nightly` once up
// front so the installation, if needed, happens only once per test process.
//
// A per-process `Once` is sufficient for now because this is currently the only
// integration test binary that prepares the nightly toolchain. If that changes,
// we may need a cross-process lock instead.
fn ensure_nightly_toolchain_installed() {
    static INIT: Once = Once::new();
    INIT.call_once(|| {
        Command::new("rustc")
            .args(["+nightly", "--version"])
            .assert()
            .success();
    });
}

fn copy_package_fixtures(workspace: &TempDir, fixture_name: &str) {
    let project_manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let src = PathBuf::from(format!(
        "{project_manifest_dir}/tests/fixtures/packages/{fixture_name}"
    ));

    assert!(
        src.is_dir(),
        "Fixture directory does not exist: {}",
        src.display()
    );

    workspace
        .copy_from(src, &["Cargo.toml", "**/*.rs", "**/*.md"])
        .unwrap();
}

fn insert_crate_doc_comment(workspace: &Path, doc_comment: &str) {
    assert!(!doc_comment.is_empty());
    assert!(doc_comment.ends_with('\n'));

    let librs_path = workspace.join("src/lib.rs");
    let content = fs::read_to_string(&librs_path).unwrap();
    let new_content = format!("{doc_comment}{content}");
    fs::write(&librs_path, &new_content).unwrap();
}

fn sync_readme(workspace: &Path) {
    let exe = env::var("CARGO_BIN_EXE_cargo-sync-rdme").unwrap();

    Command::new(exe)
        .current_dir(workspace)
        .args(["--toolchain", "nightly", "--allow-no-vcs"])
        .assert()
        .success();
}

fn run_rustdoc(workspace: &Path) {
    let mut cmd = Command::new("cargo");
    cmd.current_dir(workspace)
        .args(["+nightly", "doc", "--no-deps"])
        .assert()
        .success();
}

fn collect_links_from_markdown(md: &Path, crate_name: &str) -> Vec<(String, String)> {
    let content = fs::read_to_string(md).unwrap();
    let parser = Parser::new(&content);
    let mut links = vec![];
    let mut in_span = false;
    let mut url_prefix = HTML_ROOT_URL.to_owned();
    if !url_prefix.ends_with('/') {
        url_prefix.push('/');
    }
    url_prefix.push_str(crate_name);
    if !url_prefix.ends_with('/') {
        url_prefix.push('/');
    }
    for event in parser {
        match event {
            Event::Html(html) if html.as_ref().trim() == SPAN_START_MARKER => in_span = true,
            Event::Html(html) if html.as_ref().trim() == SPAN_END_MARKER => in_span = false,
            Event::Start(Tag::Link {
                dest_url, title, ..
            }) if in_span => {
                let relative_url = dest_url
                    .strip_prefix(&url_prefix)
                    .unwrap_or(&dest_url)
                    .to_owned();
                links.push((relative_url, title.into_string()));
            }
            _ => {}
        }
    }
    links
}

fn collect_links_from_html(html: &Path) -> Vec<(String, String)> {
    let content = fs::read_to_string(html).unwrap();
    let start = content.find(SPAN_START_MARKER).unwrap();
    let end = content.find(SPAN_END_MARKER).unwrap();
    let fragment = &content[start + SPAN_START_MARKER.len()..end];
    let fragment = Html::parse_fragment(fragment);
    let selector = Selector::parse("a").unwrap();
    fragment
        .select(&selector)
        .map(|element| {
            let href = element.value().attr("href").unwrap_or("").to_owned();
            let title = element.value().attr("title").unwrap_or("").to_owned();
            (href, title)
        })
        .collect()
}

#[rstest]
#[case::self_module("module", false)]
#[case::self_struct("Struct", false)]
#[case::self_struct_field("Struct::field", false)]
#[case::self_tuple_struct_field("TupleStruct::0", false)]
#[case::self_union("Union", false)]
#[case::self_union_field("Union::field1", false)]
#[case::self_enum("Enum", false)]
#[case::self_enum_variant("Enum::Variant", false)]
#[ignore = "rustdoc generates incorrect title for variant fields. expected: 'field Enum::Struct::field', actual: 'field Enum::field'. see <https://github.com/rust-lang/rust/issues/161028>"]
#[case::self_enum_variant_field("Enum::Struct::field", false)]
#[case::self_enum_variant_field_ignore_title("Enum::Struct::field", true)]
#[ignore = "rustdoc generates incorrect title for tuple variant fields. expected: 'field Enum::Tuple::0', actual: 'field Enum::0'. see <https://github.com/rust-lang/rust/issues/161028>"]
#[case::self_enum_tuple_variant_field("Enum::Tuple::0", false)]
#[case::self_enum_tuple_variant_field_ignore_title("Enum::Tuple::0", true)]
#[case::self_type_alias("TypeAlias", false)]
#[case::self_required_method("Trait::method", false)]
#[case::self_provided_method("Trait::provided_method", false)]
#[case::self_required_assoc_fn("Trait::assoc_fn", false)]
#[case::self_provided_assoc_fn("Trait::provided_assoc_fn", false)]
#[case::self_required_assoc_const("Trait::CONST", false)]
#[case::self_required_assoc_ty("Trait::Type", false)]
#[case::self_trait_impl_method("Struct::method", false)]
#[case::self_trait_impl_method_overrides_default("Struct::provided_method", false)]
#[case::self_trait_impl_assoc_fn("Struct::assoc_fn", false)]
#[case::self_trait_impl_assoc_const("Struct::CONST", false)]
#[case::self_trait_impl_associated_ty("Struct::Type", false)]
#[case::self_inherent_method("Struct::inhr_method", false)]
#[case::self_inherent_assoc_fn("Struct::inhr_assoc_fn", false)]
#[case::self_inherent_assoc_const("Struct::INHR_CONST", false)]
#[case::self_const("CONSTANT", false)]
#[case::self_static("STATIC", false)]
#[case::self_fn("function", false)]
#[case::self_declarative_macro("declarative_macro", false)]
#[ignore = "cargo-sync-rdme currently generates path containing private module, but rustdoc generates path without private module"]
#[case::self_reexported_from_private_module("ReexportedFromPrivateMod", false)]
#[case::self_foreign_function("foreign_function", false)]
#[case::self_foreign_static("FOREIGN_STATIC", false)]
fn generated_links_match_rustdoc(#[case] label: &str, #[case] ignore_title_mismatch: bool) {
    ensure_nightly_toolchain_installed();

    let workspace = TempDir::new().unwrap();
    let readme_path = workspace.child("README.md");
    let crate_name = "link_showcase";
    let rustdoc_html_path = workspace.child(format!("target/doc/{crate_name}/index.html"));

    copy_package_fixtures(&workspace, crate_name);

    let doc_comment = indoc::formatdoc! {r"
        //! {SPAN_START_MARKER}
        //! [{label}]
        //! {SPAN_END_MARKER}
    "};

    insert_crate_doc_comment(&workspace, &doc_comment);
    sync_readme(&workspace);
    run_rustdoc(&workspace);

    let md_links = collect_links_from_markdown(&readme_path, crate_name);
    let html_links = collect_links_from_html(&rustdoc_html_path);

    if ignore_title_mismatch {
        if md_links != html_links {
            eprintln!("Markdown links: {md_links:?}");
            eprintln!("HTML links: {html_links:?}");
            let md_links: Vec<_> = md_links.iter().map(|(url, _)| url).collect();
            let html_links: Vec<_> = html_links.iter().map(|(url, _)| url).collect();
            assert_eq!(md_links, html_links);
        }
    } else {
        assert_eq!(md_links, html_links);
    }
    assert!(!md_links.is_empty());
}
