//! Integration test to ensure that the generated links match the links generated by rustdoc.

use rstest::rstest;
use similar_asserts::assert_eq;
use test_helper::{self as helper, SPAN_END_MARKER, SPAN_START_MARKER, Workspace};

#[rstest]
#[case("stable", "std::fmt::Result")]
#[case("1.96.0", "std::fmt::Result")]
#[case("beta", "std::fmt::Result")]
#[case("nightly", "std::fmt::Result")]
fn generated_links_match_rustdoc(#[case] toolchain: &'static str, #[case] label: &str) {
    helper::assert_nightly_toolchain_installed();
    helper::assert_toolchain_installed(toolchain);

    let crate_name = "empty";
    let workspace = Workspace::from_fixture(crate_name);
    let readme_path = workspace
        .metadata()
        .root_package()
        .unwrap()
        .readme()
        .unwrap();
    let rustdoc_html_path = workspace
        .metadata()
        .target_directory
        .join("doc")
        .join(crate_name)
        .join("index.html");

    let doc_comment = indoc::formatdoc! {r"
        //! {SPAN_START_MARKER}
        //! [{label}]
        //! {SPAN_END_MARKER}
    "};

    helper::insert_crate_doc_comment(&workspace, "src/lib.rs", &doc_comment);
    helper::sync_readme_with_toolchain(&workspace, toolchain);
    helper::run_rustdoc_with_toolchain(&workspace, toolchain);

    let md_links = helper::collect_links_from_markdown(readme_path, crate_name);
    let html_links = helper::collect_links_from_html(&rustdoc_html_path);
    assert_eq!(md_links, html_links);
    assert!(!md_links.is_empty());
}
