[package]
name = "cargo-sync-rdme-example-lib"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
repository.workspace = true
license.workspace = true
publish = false

[package.metadata.cargo-sync-rdme.badge]
badges = {}

[package.metadata.cargo-sync-rdme.rustdoc]
html-root-url = "https://gifnksm.github.io/cargo-sync-rdme/"

[dependencies]
async-trait = "0.1.92"
cargo_metadata.workspace = true
num = { version = "0.4.3", features = ["num-bigint"] }
serde = { version = "1.0.229", features = ["derive"] }

[lints]
workspace = true
