name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.set-values.outputs.rust }}
      os: ${{ steps.set-values.outputs.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - name: Set matrix values
        id: set-values
        run: |
          root_package_id="$(cargo metadata --format-version 1 | jq -cr '.resolve.root')"
          root_package="$(cargo metadata --format-version 1 | jq -c --arg pkgid "${root_package_id}" '.packages[] | select(.id == $pkgid)')"
          echo "${root_package}" | jq -c '{ root_package: .name }'

          msrv="$(echo "${root_package}" | jq '.rust_version')"
          rust="$(echo "[\"stable\", ${msrv}]" | jq -c)"
          echo "rust=${rust}" >> "$GITHUB_OUTPUT"

          os="$(echo '["ubuntu-latest", "macos-latest", "windows-latest"]' | jq -c)"
          echo "os=${os}" >> "$GITHUB_OUTPUT"

          jq -n --argjson rust "${rust}" --argjson os "${os}" '{ rust: $rust, os: $os }'
        shell: bash

  check-rust:
    name: Check (rust)
    needs: set-matrix
    strategy:
      fail-fast: true
      matrix:
        rust: ${{ fromJSON(needs.set-matrix.outputs.rust) }}
        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      MISE_RUST_VERSION: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run ci:check-rust
        shell: bash

  check-rustdoc:
    name: Check (rustdoc)
    needs: set-matrix
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      MISE_RUST_VERSION: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run ci:check-rustdoc
        shell: bash

  check-unused-deps:
    name: Check (unused dependencies)
    needs: set-matrix
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      MISE_RUST_VERSION: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run ci:check-unused-deps
        shell: bash

  lint-rustfmt:
    name: Lint (rustfmt)
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run ci:lint-rustfmt
        shell: bash

  lint-rust:
    name: Lint (rust)
    needs: set-matrix
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      MISE_RUST_VERSION: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run ci:lint-rust
        shell: bash

  test-rust:
    name: Test (rust)
    needs: set-matrix
    strategy:
      fail-fast: true
      matrix:
        rust: ${{ fromJSON(needs.set-matrix.outputs.rust) }}
        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      MISE_RUST_VERSION: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run ci:test-rust
        shell: bash

  coverage-rust-test:
    name: Coverage (rust test)
    needs: set-matrix
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      MISE_RUST_VERSION: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run ci:coverage-rust-test
        shell: bash
      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/codecov-test.json
          fail_ci_if_error: false

  coverage-rust-run:
    name: Coverage (rust run)
    needs: set-matrix
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      MISE_RUST_VERSION: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run ci:coverage-rust-run
        shell: bash
      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/codecov-run.json
          fail_ci_if_error: false

  check-release:
    name: Check (release)
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      MISE_RUST_VERSION: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run check:release --skip-ci
        shell: bash

  lint-toml:
    name: Lint (toml)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: mise run ci:lint-toml
        shell: bash

  lint-workflow:
    name: Lint (workflow)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: mise run ci:lint-workflow
        shell: bash

  lint-spelling:
    name: Lint (spelling)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: mise run ci:lint-spelling
        shell: bash

  sync-markdown:
    name: Sync (markdown)
    needs: set-matrix
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      MISE_RUST_VERSION: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run ci:sync-markdown
        shell: bash

  lint-markdown:
    name: Lint (markdown)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: mise run ci:lint-markdown
        shell: bash

  lint-editorconfig:
    name: Lint (editorconfig)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: mise run ci:lint-editorconfig
        shell: bash

  ci-complete:
    needs:
      - set-matrix
      - lint-rustfmt
      - check-rust
      - check-rustdoc
      - check-unused-deps
      - lint-rust
      - test-rust
      - coverage-rust-test
      - coverage-rust-run
      - check-release
      - lint-toml
      - lint-workflow
      - lint-spelling
      - sync-markdown
      - lint-markdown
      - lint-editorconfig
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: CI complete
        run: |
          if ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}; then
            echo "CI succeeded"
          else
            echo "CI failed"
            exit 1
          fi
        shell: bash
