name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    uses: gifnksm/rust-template/.github/workflows/reusable-ci.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ci-complete:
    needs: ci
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          if ${{ needs.ci.result == 'success' }}; then
            echo "CI succeeded"
            exit 0
          else
            echo "CI failed"
            exit 1
          fi
